### ISSUE TITLE
no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"

### ISSUE THREAD

**Issue by ilie-pandaciuc** [loft-sh/component-chart#97]
I guess in Kubernetes 1.25 they removed “autoscaling/v2beta1”.
The error that I get is:
`Error: UPGRADE FAILED: resource mapping not found for name: "my-release"  no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"  `

Can you please update the charts to support k8s v1.25+? Thank you

**Comment by pablorsk** [comment]
Hi @ilie-pandaciuc!

could you solve it? If so, how did you achieve it?

**Comment by pablorsk** [comment]
Quickly fix: remove all helm secrets on server and deploy again.
